//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Power.Revit.Build.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Programs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Programs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Power.Revit.Build.Tasks.Properties.Programs", typeof(Programs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OR_GREATER.
        /// </summary>
        internal static string Constant_OrGreater {
            get {
                return ResourceManager.GetString("Constant_OrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string Constant_Revit {
            get {
                return ResourceManager.GetString("Constant_Revit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullPath.
        /// </summary>
        internal static string Metadata_FullPath {
            get {
                return ResourceManager.GetString("Metadata_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredReference.
        /// </summary>
        internal static string Metadata_RequiredReference {
            get {
                return ResourceManager.GetString("Metadata_RequiredReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching {0}: removing &apos;ManifestSettings&apos;.
        /// </summary>
        internal static string Msg_RemovingManifestSettings {
            get {
                return ResourceManager.GetString("Msg_RemovingManifestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManifestSettings.
        /// </summary>
        internal static string XName_ManifestSettings {
            get {
                return ResourceManager.GetString("XName_ManifestSettings", resourceCulture);
            }
        }
    }
}
